; CastFlux Windows Installer (Inno Setup)
; Compile: ISCC.exe installer.iss

#define MyAppName "CastFlux"
#ifndef MyAppVersion
#define MyAppVersion "1.0.9"
#endif
#define MyAppPublisher "cybertronic23"
#define MyAppURL "https://github.com/cybertronic23/castflux"

[Setup]
AppId={{584E0B1C-1C8B-4B8E-8F6C-8D6E3F2A1C5D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={localappdata}\Programs\CastFlux
DefaultGroupName=CastFlux
DisableProgramGroupPage=yes
OutputDir=..\dist
OutputBaseFilename=CastFlux_Setup_{#MyAppVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=lowest
ArchitecturesInstallIn64BitMode=x64compatible
DisableWelcomePage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"

[Files]
; 核心 Python 包
Source: "..\src\castflux\*.py"; DestDir: "{app}\src\castflux"; Flags: ignoreversion
Source: "..\pyproject.toml"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\docs\WINDOWS_QUICK_START.md"; DestDir: "{app}\docs"; Flags: ignoreversion
Source: "..\LICENSE"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\uv.lock"; DestDir: "{app}"; Flags: ignoreversion
; Environment template only. setup creates an empty .env so placeholder keys are never used.
Source: "..\.env.example"; DestDir: "{app}"; Flags: ignoreversion
; 脚本
Source: "run_gui.bat"; DestDir: "{app}\scripts"; Flags: ignoreversion
Source: "setup_gui.bat"; DestDir: "{app}\scripts"; Flags: ignoreversion
Source: "windows_bootstrap.ps1"; DestDir: "{app}\scripts"; Flags: ignoreversion
Source: "castflux.bat"; DestDir: "{app}\scripts"; Flags: ignoreversion
Source: "collect_support_logs.bat"; DestDir: "{app}\scripts"; Flags: ignoreversion
; Offline bootstrap payload generated by scripts/build_installer.ps1
Source: "vendor\downloads\python-3.11.9-amd64.exe"; DestDir: "{app}\runtime\downloads"; Flags: ignoreversion skipifsourcedoesntexist
Source: "vendor\downloads\ffmpeg-release-essentials.zip"; DestDir: "{app}\runtime\downloads"; Flags: ignoreversion skipifsourcedoesntexist
Source: "vendor\wheelhouse\*"; DestDir: "{app}\runtime\wheelhouse"; Flags: ignoreversion recursesubdirs createallsubdirs skipifsourcedoesntexist
; 输出目录占位
Source: "..\output_slices\.gitkeep"; DestDir: "{app}\output_slices"; Flags: ignoreversion

[Icons]
Name: "{userdesktop}\CastFlux"; Filename: "{app}\scripts\run_gui.bat"; WorkingDir: "{app}"; Comment: "CastFlux"
Name: "{group}\CastFlux"; Filename: "{app}\scripts\run_gui.bat"; WorkingDir: "{app}"
Name: "{group}\打包 CastFlux 故障日志"; Filename: "{app}\scripts\collect_support_logs.bat"; WorkingDir: "{app}"
Name: "{group}\Uninstall CastFlux"; Filename: "{uninstallexe}"

[Run]
; 安装私有 Python、ffmpeg、项目依赖（窗口可见，让用户看到进度）
Filename: "{app}\scripts\setup_gui.bat"; Parameters: "--installer"; StatusMsg: "正在配置环境（自动安装 Python / ffmpeg / 依赖，需几分钟）..."; Flags: waituntilterminated shellexec
; 安装完成，可选启动 GUI
Filename: "{app}\scripts\run_gui.bat"; Description: "启动 CastFlux"; Flags: postinstall nowait skipifsilent shellexec unchecked

[UninstallDelete]
Type: filesandordirs; Name: "{app}\.venv"
Type: filesandordirs; Name: "{app}\runtime"
Type: filesandordirs; Name: "{app}\scripts\ffmpeg"
